export enum CreationFeeStatus {
  HELD = 'HELD',
  SETTLED = 'SETTLED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
  REFUND_RECONCILIATION_REQUIRED = 'REFUND_RECONCILIATION_REQUIRED',
  RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED',
}
